### ISSUE TITLE
TTL is unitless in the display

### ISSUE THREAD

**Issue by CtrlZvi** [RiotGames/key-conjurer#12]
Could the TTL display be updated to include the units? I know from experience that the numbers represent hours, but the UI does not make that clear, and coming from a DNS background, my brain keeps wanting it to be seconds.

**Comment by TheM0ng00se** [comment]
Hey @CtrlZvi , this displays the units now. Please feel free to reopen if you think this is not addressed.

**Comment by TheM0ng00se** [comment]
TL;DR This is the WebUI for Keyconjurer displaying just an integer without units associated with it.

**Comment by TheM0ng00se** [comment]
Closing out, @CtrlZvi , please reopen if you have issues.
