### ISSUE TITLE
Login Success Feedback

### ISSUE THREAD

**Issue by rnikoopour** [RiotGames/key-conjurer#16]
Failed logins give failure feedback but success logins do not provide any feedback.

Could we get a "Login Success!" message on success?

**Comment by TheM0ng00se** [comment]
If primary authentication method (i.e. IDP/LDAP) has expired, the user will still get a MFA push, but keyconjurer will fail. Executing 'keyconjurer login', and then reissuing command will succeed but the user doesn't get that feedback.
